version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: sup-vinci
      POSTGRES_DB: renfo-backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
